
ELE_MODEL: # element recognition model -- logo only
  CFG_PATH: phishpedia/configs/detectron2_configs/faster_rcnn.yaml
  WEIGHTS_PATH: phishpedia/weights/detectron2_weights/rcnn_bet365.pth
  DETECT_THRE: 0.05

SIAMESE_MODEL:
  NUM_CLASSES: 277 # number of brands, users don't need to modify this even the targetlist is expanded
  WEIGHTS_PATH: phishpedia/weights/siamese_weights/resnetv2_rgb_new.pth.tar
  TARGETLIST_PATH: phishpedia/datasets/expand_targetlist.zip
  MATCH_THRE: 0.83 # FIXME: threshold is 0.87 in phish-discovery?
  DOMAIN_MAP_PATH: phishpedia/weights/siamese_weights/domain_map.pkl

