name: Build and Test Images

on:
  push:
    branches: [ "main", "feat-setup-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: phishpedia
          file: docker/Dockerfile.cpu
          outputs: type=docker,dest=/tmp/phishpedia.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: phishpedia-image
          path: /tmp/phishpedia.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: phishpedia-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/phishpedia.tar
      - name: Test image
        run: docker run --rm phishpedia python run.py
